services:
  - type: web
    name: dj-acoustid-backend
    env: python

    buildCommand: |
      apt-get update -y
      apt-get install -y ffmpeg chromaprint
      which fpcalc || true
      find / -name fpcalc || true
      pip install -r requirements.txt

    startCommand: python app.py
