services:
  - type: web
    name: dj-acoustid-backend
    env: python

    buildCommand: |
      apt-get update -y
      apt-get install -y ffmpeg libchromaprint-tools
      which fpcalc || true
      fpcalc --version || true
      pip install -r requirements.txt

    startCommand: python app.py
